 #!/bin/bash

 pbip=`grep "IPADDR0" /etc/sysconfig/network-scripts/ifcfg-eth0`
 pbip=${pbip#*=}

 if [ -z "$pbip" ]; then
	     echo "이미 설정되어 있거나 잘못 설정되어 있습니다."
	         exit 1
 fi

 pbgw=`grep "GATEWAY0" /etc/sysconfig/network-scripts/ifcfg-eth0`
 pbgw=${pbgw#*=}

 pbpref=`grep "PREFIX0" /etc/sysconfig/network-scripts/ifcfg-eth0`
 pbpref=${pbpref#*=}
 echo $pbip / $pbgw / $pbpref 

 pvip=`grep "IPADDR1" /etc/sysconfig/network-scripts/ifcfg-eth0`
 pvip=${pvip#*=}

 pvpref=`grep "PREFIX1" /etc/sysconfig/network-scripts/ifcfg-eth0`
 pvpref=${pvpref#*=}
 pvpref=${pvpref//\"/}
 echo $pvip / $pvpref 

 dns1=`grep "DNS1" /etc/sysconfig/network-scripts/ifcfg-eth0`
 dns2=`grep "DNS2" /etc/sysconfig/network-scripts/ifcfg-eth0`
 dns3=`grep "DNS3" /etc/sysconfig/network-scripts/ifcfg-eth0`
 dns1=${dns1#*=}
 dns2=${dns2#*=}
 dns3=${dns3#*=}

 echo $dns1, $dns2, $dns3

 cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
#Public Network
DEVICE=eth0
BOOTPROTO=none
ONBOOT=yes
IPADDR=$pbip
PREFIX=$pbpref
GATEWAY=$pbgw
EOF

cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth0:0
#private network
DEVICE=eth0:0
BOOTPROTO=none
ONBOOT=yes
IPADDR=$pvip
PREFIX=$pvpref
EOF

systemctl restart network

cat << EOF > /etc/resolv.conf
# Generated by NetworkManager
search members.linode.com
nameserver $dns1
nameserver $dns2
nameserver $dns3
EOF

systemctl restart network

